language: node_js
node_js:
- '4.1.1'
sudo: false
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: F9PdYmFKwStPC7zVWBjYMB7AsO3/nIhvMkcTNEo8V40frb6do1rBMOm/GwYahjuHWsv4YYSuYsQ+tPZnAU5KiUB68m7LxNa0eyZp2sPV7wgybJwTsK9ItUCtmA99FTYIeAl78iZOUO9taH2TjFCZLZy+xxbE2ggp6wxwNAD3n2U=
  on:
    tags: true
    all_branches: true
