language: node_js
node_js:
- 5.6
before_script:
- gem install percy-cli
after_success:
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && npm run perceptual-diff'
sudo: false
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: F9PdYmFKwStPC7zVWBjYMB7AsO3/nIhvMkcTNEo8V40frb6do1rBMOm/GwYahjuHWsv4YYSuYsQ+tPZnAU5KiUB68m7LxNa0eyZp2sPV7wgybJwTsK9ItUCtmA99FTYIeAl78iZOUO9taH2TjFCZLZy+xxbE2ggp6wxwNAD3n2U=
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: Rq5z6QcfAoC5/ciD6Nzk9bkIk1bXnKEyeJUBnA6y0a43ULLjumNHsmIDbrUvlBIc91gVS/LhyykHts/Nq6L4y1J2cGUyo3kCdzQpi5y6v2Ton1cTz90TfIEJrcK8IL5JMstmR9aq58Warl67jJz00FuToA6f6Mf7BtA5RngqnCA=
